# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do concedente', max_length=50)),
                ('nome_responsavel', models.CharField(help_text='Nome do respons\xe1vel pelo concedente', max_length=100)),
                ('codigo_responsavel', models.CharField(help_text='C\xf3digo do respons\xe1vel pelo concedente', max_length=20)),
                ('cargo_responsavel', models.CharField(help_text='Nome do cargo do respons\xe1vel pelo concedente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0, help_text='N\xfamero do Conv\xeanio')),
                ('numero_processo', models.CharField(help_text='Situa\xe7\xe3o da aplica\xe7\xe3o de recursos.', max_length=20)),
                ('numero_interno', models.CharField(help_text='Situa\xe7\xe3o da aplica\xe7\xe3o de recursos.', max_length=20)),
                ('objeto_convenio', models.TextField(help_text='Objeto do Conv\xeanio', max_length=1000)),
                ('justificativa_convenio', models.TextField(help_text='Justificativa do Conv\xeanio', max_length=1000)),
                ('valor_global', models.DecimalField(decimal_places=2, help_text='Valor global do conv\xeanio', max_digits=10)),
                ('valor_repasse', models.DecimalField(decimal_places=2, help_text='Valor repassado pelo concedente', max_digits=10)),
                ('valor_contrapartida_total', models.DecimalField(decimal_places=2, help_text='Valor da contrapartida do convenente', max_digits=10)),
                ('valor_contrapartida_financeira', models.DecimalField(decimal_places=2, help_text='Valor da contrapartida financeira do convenente', max_digits=10)),
                ('valor_contrapartida_bens_servicos', models.DecimalField(decimal_places=2, help_text='Valor da contrapartida em bens e servi\xe7os do convenente', max_digits=10)),
                ('data_publicacao', models.DateField(help_text='Data de publica\xe7\xe3o do conv\xeanio')),
                ('data_assinatura', models.DateField(help_text='Data assinatura do conv\xeanio')),
                ('data_inicio_vigencia', models.DateField(help_text='Data de in\xedcio do conv\xeanio')),
                ('data_termino_vigencia', models.DateField(help_text='Data de t\xe9rmino do conv\xeanio')),
                ('assinado', models.BooleanField(default=False)),
                ('aditivo', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('empenhado', models.BooleanField(default=False)),
                ('permite_ajuste_cronograma_fisico', models.BooleanField(default=False)),
                ('concedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.Concedente')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descri\xe7\xe3o do equipamento', max_length=100)),
                ('quantidade_equipamento', models.IntegerField(default=0, help_text='N\xfamero de equipamentos no munic\xedpio')),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadeConvenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Modalidade do conv\xeanio', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ibge', models.IntegerField(default=0, help_text='C\xf3digo do munic\xedpio no IBGE')),
                ('cod_siconv', models.IntegerField(default=0, help_text='C\xf3digo do munic\xedpio no SICONV')),
                ('nome', models.CharField(help_text='Nome do munic\xedpio', max_length=100)),
                ('populacao', models.IntegerField(default=0, help_text='Popula\xe7\xe3o do munic\xedpio')),
                ('idh', models.DecimalField(decimal_places=3, help_text='\xcdndice de Desenvolvimento Humano do munic\xedpio', max_digits=3)),
                ('mortalidade', models.DecimalField(decimal_places=3, help_text='Mortalidade do munic\xedpio', max_digits=3)),
                ('uf', models.CharField(help_text='UF do munic\xedpio', max_length=2)),
                ('latitude', models.DecimalField(decimal_places=5, help_text='Latitude do munic\xedpio', max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=5, help_text='Longitude do munic\xedpio', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza_aplicacao', models.CharField(help_text='Natureza da aplica\xe7\xe3o', max_length=100)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.Convenio')),
                ('municipio_aplicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('identificacao', models.CharField(max_length=100)),
                ('nome_responsavel', models.CharField(help_text='Nome do respons\xe1vel pelo proponente', max_length=100)),
                ('cargo_responsavel', models.CharField(help_text='Cargo do respons\xe1vel pelo proponente', max_length=50)),
                ('cep', models.CharField(help_text='CEP do proponente', max_length=10)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='QualificacaoProponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacao', models.CharField(help_text='Qualifica\xe7\xe3o do proponente do conv\xeanio', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoAplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Situa\xe7\xe3o da aplica\xe7\xe3o de recursos do conv\xeanio', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoConvenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Situa\xe7\xe3o do conv\xeanio', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoPublicacaoConvenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Situa\xe7\xe3o da publica\xe7\xe3o do conv\xeanio', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_despesa', models.CharField(help_text='Tipo da despesa', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(help_text='Bairro onde localiza-se a Unidade de Sa\xfade', max_length=100)),
                ('logradouro', models.CharField(help_text='Logradouro onde localiza-se a Unidade de Sa\xfade', max_length=100)),
                ('cep', models.CharField(help_text='CEP no qual localiza-se a Unidade de Sa\xfade', max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.Municipio')),
            ],
        ),
        migrations.AddField(
            model_name='proponente',
            name='qualificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.QualificacaoProponente'),
        ),
        migrations.AddField(
            model_name='planoaplicacao',
            name='situacao_aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.SituacaoAplicacao'),
        ),
        migrations.AddField(
            model_name='planoaplicacao',
            name='tipo_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.TipoDespesa'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='municipio',
            field=models.ForeignKey(help_text='Cidade onde est\xe1 o equipamento', on_delete=django.db.models.deletion.CASCADE, to='carcara.Municipio'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.ModalidadeConvenio'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='municipio_convenente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.Municipio'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='situacao_convenio',
            field=models.ForeignKey(help_text='Status do conv\xeanio.', on_delete=django.db.models.deletion.CASCADE, to='carcara.SituacaoConvenio'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='situacao_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcara.SituacaoPublicacaoConvenio'),
        ),
    ]
