# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carcara', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenio',
            old_name='justificativa_convenio',
            new_name='justificativa',
        ),
        migrations.RenameField(
            model_name='convenio',
            old_name='objeto_convenio',
            new_name='objeto',
        ),
        migrations.RenameField(
            model_name='convenio',
            old_name='situacao_convenio',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='planoaplicacao',
            old_name='natureza_aplicacao',
            new_name='natureza',
        ),
        migrations.RenameField(
            model_name='planoaplicacao',
            old_name='situacao_aplicacao',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='tipodespesa',
            old_name='nome_tipo_despesa',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='municipio_convenente',
        ),
        migrations.AddField(
            model_name='convenio',
            name='proponente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='carcara.Proponente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proponente',
            name='tipo_identificacao',
            field=models.CharField(default='', help_text='Tipo de identifica\xe7\xe3o do proponente', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proponente',
            name='identificacao',
            field=models.CharField(help_text='Identifica\xe7\xe3o do proponente', max_length=100),
        ),
    ]
